### Home
GET http://localhost:3000/

### Get All User
GET http://localhost:3000/user/getAll

### Create user
POST http://localhost:3000/user/create
Content-Type: application/json

{
  "name": "AlexDvor",
  "email": "alex.dvor@example.com"
}
